/** Configurable mouse icons and canvas trails for the skin drawer. */
(function (global) {
    'use strict';
    if (global.__READING_ORIGINAL_UI__ || /reading-practice-unified\.html$/i.test((global.location && global.location.pathname) || '')) return;
    var KEY='skin_pointer_settings_v2',DB='jimmy_image_skin_cache',STORE='assets',IMAGE_KEY='custom-pointer-icon';
    var reduced=global.matchMedia&&global.matchMedia('(prefers-reduced-motion: reduce)').matches;
    var fine=global.matchMedia&&global.matchMedia('(hover:hover) and (pointer:fine)').matches;
    var styles=['halo','sparkle','bubble','ribbon','custom'],settings=read(),canvas,ctx,icon,panel,raf=0,points=[],x=-100,y=-100,visible=false,last=0,dpr=1,objectUrl='';
    function clamp(v,min,max){v=Number(v);return Number.isFinite(v)?Math.min(max,Math.max(min,v)):min;}
    function read(){var v={};try{v=JSON.parse(localStorage.getItem(KEY)||'{}');}catch(_){}return{enabled:v.enabled!==false,style:styles.indexOf(v.style)>=0?v.style:'halo',size:clamp(v.size==null?32:v.size,18,72)};}
    function save(){try{localStorage.setItem(KEY,JSON.stringify(settings));}catch(_){}}
    function dbOpen(){return new Promise(function(resolve,reject){if(!global.indexedDB)return reject();var q=indexedDB.open(DB,1);q.onupgradeneeded=function(){if(!q.result.objectStoreNames.contains(STORE))q.result.createObjectStore(STORE);};q.onsuccess=function(){resolve(q.result);};q.onerror=function(){reject(q.error);};});}
    function dbPut(blob){return dbOpen().then(function(db){return new Promise(function(resolve,reject){var tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(blob,IMAGE_KEY);tx.oncomplete=function(){db.close();resolve();};tx.onerror=function(){db.close();reject(tx.error);};});});}
    function dbGet(){return dbOpen().then(function(db){return new Promise(function(resolve,reject){var q=db.transaction(STORE).objectStore(STORE).get(IMAGE_KEY);q.onsuccess=function(){db.close();resolve(q.result||null);};q.onerror=function(){db.close();reject(q.error);};});});}
    function status(text,error){var el=panel&&panel.querySelector('.skin-pointer-status');if(el){el.textContent=text;el.classList.toggle('is-error',!!error);}}
    function customImage(blob){if(!blob||!icon)return;if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=URL.createObjectURL(blob);var url='url("'+objectUrl.replace(/"/g,'%22')+'")';icon.style.setProperty('--pointer-custom-image',url);icon.style.setProperty('--pointer-custom-empty','none');var preview=panel&&panel.querySelector('[data-pointer-style="custom"] .skin-pointer-preset__icon');if(preview){preview.style.backgroundImage=url;preview.style.backgroundSize='contain';preview.style.backgroundPosition='center';preview.style.backgroundRepeat='no-repeat';preview.textContent='';}}
    function stage(){if(canvas)return;canvas=document.createElement('canvas');canvas.id='skin-pointer-canvas';canvas.setAttribute('aria-hidden','true');icon=document.createElement('i');icon.id='skin-pointer-icon';icon.setAttribute('aria-hidden','true');document.body.appendChild(canvas);document.body.appendChild(icon);ctx=canvas.getContext('2d');resize();global.addEventListener('resize',resize,{passive:true});}
    function resize(){if(!canvas)return;dpr=Math.min(global.devicePixelRatio||1,2);canvas.width=Math.round(global.innerWidth*dpr);canvas.height=Math.round(global.innerHeight*dpr);canvas.style.width=global.innerWidth+'px';canvas.style.height=global.innerHeight+'px';ctx.setTransform(dpr,0,0,dpr,0,0);}
    function color(){return getComputedStyle(document.documentElement).getPropertyValue('--skin-accent').trim()||'#6d5bd0';}
    function halo(){points.forEach(function(p,i){var life=Math.max(0,1-p.age/520),r=2+life*(4+i/Math.max(points.length,1)*4);ctx.globalAlpha=life*.42;ctx.strokeStyle=color();ctx.lineWidth=1.2;ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.stroke();});}
    function sparkle(){points.forEach(function(p,index){var life=Math.max(0,1-p.age/650),r=2+life*(3+index%3);ctx.globalAlpha=life*.76;ctx.fillStyle=color();ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.age*.004+index);ctx.beginPath();for(var i=0;i<8;i++){var rr=i%2?r*.32:r,a=Math.PI/4*i-Math.PI/2;if(!i)ctx.moveTo(Math.cos(a)*rr,Math.sin(a)*rr);else ctx.lineTo(Math.cos(a)*rr,Math.sin(a)*rr);}ctx.closePath();ctx.fill();ctx.restore();});}
    function bubble(){points.forEach(function(p,index){var life=Math.max(0,1-p.age/820),r=2+(1-life)*7+index%3;ctx.globalAlpha=life*.46;ctx.strokeStyle=color();ctx.lineWidth=1;ctx.beginPath();ctx.arc(p.x,p.y-(1-life)*9,r,0,Math.PI*2);ctx.stroke();});}
    function ribbon(){if(points.length<2)return;var g=ctx.createLinearGradient(points[0].x,points[0].y,points[points.length-1].x,points[points.length-1].y);g.addColorStop(0,'rgba(255,255,255,0)');g.addColorStop(1,color());ctx.globalAlpha=.58;ctx.strokeStyle=g;ctx.lineWidth=5;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);for(var i=1;i<points.length-1;i++){ctx.quadraticCurveTo(points[i].x,points[i].y,(points[i].x+points[i+1].x)/2,(points[i].y+points[i+1].y)/2);}ctx.lineTo(points[points.length-1].x,points[points.length-1].y);ctx.stroke();}
    function render(time){raf=0;if(!settings.enabled||!ctx)return;var delta=last?Math.min(34,time-last):16.7;last=time;points.forEach(function(p){p.age+=delta;});var age=settings.style==='bubble'?820:settings.style==='sparkle'?650:settings.style==='ribbon'?420:520;points=points.filter(function(p){return p.age<age;});ctx.clearRect(0,0,global.innerWidth,global.innerHeight);if(visible&&settings.style!=='custom'){if(settings.style==='halo')halo();else if(settings.style==='sparkle')sparkle();else if(settings.style==='bubble')bubble();else if(settings.style==='ribbon')ribbon();}ctx.globalAlpha=1;if(points.length)raf=global.requestAnimationFrame(render);}
    function requestDraw(){if(!raf)raf=global.requestAnimationFrame(render);}
    function sync(){if(!panel)return;panel.dataset.style=settings.style;var toggle=panel.querySelector('.skin-pointer-toggle');toggle.setAttribute('aria-checked',settings.enabled?'true':'false');toggle.setAttribute('aria-label',settings.enabled?'关闭鼠标追踪动画':'打开鼠标追踪动画');panel.querySelectorAll('[data-pointer-style]').forEach(function(b){var active=b.dataset.pointerStyle===settings.style;b.classList.toggle('is-active',active);b.setAttribute('aria-pressed',active?'true':'false');});panel.querySelector('[data-pointer-size]').value=settings.size;panel.querySelector('[data-pointer-size-output]').textContent=settings.size+'px';}
    function apply(){stage();document.body.classList.toggle('skin-pointer-enabled',settings.enabled);document.body.classList.toggle('skin-pointer-visible',settings.enabled&&visible);icon.dataset.style=settings.style;icon.style.setProperty('--pointer-size',settings.size+'px');if(!settings.enabled){points=[];ctx.clearRect(0,0,global.innerWidth,global.innerHeight);document.body.classList.remove('skin-pointer-action');}sync();}
    function choose(style){if(styles.indexOf(style)<0)return;settings.style=style;settings.enabled=true;points=[];save();apply();status(style==='custom'?'上传透明背景图片，效果会实时显示并保存在本机。':'已应用新的鼠标图标与追踪轨迹。');}
    function card(id,name,glyph){return '<button type="button" class="skin-pointer-preset" data-pointer-style="'+id+'" aria-label="使用'+name+'鼠标效果"><i class="skin-pointer-preset__icon">'+glyph+'</i><span class="skin-pointer-preset__name">'+name+'</span></button>';}
    function build(){var drawer=document.querySelector('#image-skin-panel .skin-drawer');if(!drawer||drawer.querySelector('.skin-pointer-workbench'))return;panel=document.createElement('section');panel.className='skin-pointer-workbench';panel.innerHTML='<div class="skin-pointer-head"><span class="skin-pointer-title"><b>鼠标追踪</b><small>图标与轨迹可独立开关</small></span><button type="button" class="skin-pointer-toggle" role="switch"></button></div><div class="skin-pointer-presets">'+card('halo','柔光环','◎')+card('sparkle','星屑','✦')+card('bubble','泡泡','◉')+card('ribbon','霓虹带','◆')+card('custom','自定义','＋')+'</div><div class="skin-pointer-custom"><label class="skin-pointer-upload"><input type="file" accept="image/png,image/webp,image/gif,image/jpeg"><span>上传鼠标图片</span></label><label class="skin-pointer-size"><span>图标大小 <output data-pointer-size-output></output></span><input type="range" min="18" max="72" step="1" data-pointer-size></label></div><div class="skin-pointer-status" role="status">透明 PNG 或 WebP 效果最佳，最大 3 MB。</div>';drawer.appendChild(panel);
        panel.querySelector('.skin-pointer-toggle').addEventListener('click',function(){settings.enabled=!settings.enabled;save();apply();status(settings.enabled?'鼠标追踪动画已打开。':'鼠标追踪动画已关闭。');});
        panel.querySelectorAll('[data-pointer-style]').forEach(function(b){b.addEventListener('click',function(){choose(b.dataset.pointerStyle);});});
        panel.querySelector('[data-pointer-size]').addEventListener('input',function(){settings.size=clamp(this.value,18,72);save();apply();});
        panel.querySelector('input[type="file"]').addEventListener('change',function(){var file=this.files&&this.files[0];this.value='';if(!file||!/^image\//i.test(file.type))return status('请选择 PNG、WebP、GIF 或 JPG 图片。',true);if(file.size>3*1024*1024)return status('鼠标图片请控制在 3 MB 以内。',true);status('正在保存自定义鼠标图片…');dbPut(file).then(function(){customImage(file);choose('custom');status('自定义鼠标图片已保存，刷新后仍会应用。');}).catch(function(){status('图片保存失败，请换一张较小的图片重试。',true);});});sync();}
    function move(event){if(!settings.enabled||(event.pointerType&&event.pointerType!=='mouse'))return;x=event.clientX;y=event.clientY;visible=true;document.body.classList.add('skin-pointer-visible');var action=event.target.closest&&event.target.closest('button,a,input,select,textarea,[role="button"],.suite-card,.tool-card');document.body.classList.toggle('skin-pointer-action',!!action);var scale=action?1.18:1,size=settings.size;icon.style.transform='translate3d('+(x-size/2)+'px,'+(y-size/2)+'px,0) scale('+scale+')';var prev=points[points.length-1];if(!prev||Math.hypot(x-prev.x,y-prev.y)>5)points.push({x:x,y:y,age:0});if(points.length>34)points.shift();var nx=x/Math.max(global.innerWidth,1)-.5,ny=y/Math.max(global.innerHeight,1)-.5;document.documentElement.style.setProperty('--skin-shift-x',(-nx*12).toFixed(2)+'px');document.documentElement.style.setProperty('--skin-shift-y',(-ny*8).toFixed(2)+'px');requestDraw();}
    function init(){if(!fine||reduced)return;stage();build();apply();document.addEventListener('pointermove',move,{passive:true});document.documentElement.addEventListener('mouseleave',function(){visible=false;document.body.classList.remove('skin-pointer-visible','skin-pointer-action');});document.addEventListener('visibilitychange',function(){if(document.hidden){visible=false;points=[];document.body.classList.remove('skin-pointer-visible');}});dbGet().then(function(blob){if(blob)customImage(blob);}).catch(function(){});}
    if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
    global.PointerSkins={enable:function(value){settings.enabled=!!value;save();apply();},setStyle:choose,settings:function(){return Object.assign({},settings);}};
})(typeof window!=='undefined'?window:this);